project:
  type: website
  output-dir: ../docs/
  render:
    - '*.qmd'
    - '*.md'
    - '!README.md'
    - '!index.md'
    - '!data-raw/'
website:
  title: snapr
  repo-url: https://github.com/d-morrison/snapr
  repo-actions:
    - edit
    - source
    - issue
  navbar:
    search: true
    pinned: false
    right:
      - icon: github
        href: https://github.com/d-morrison/snapr
        aria-label: snapr GitHub
    left:
      - text: Documentation
        file: man/snapr-package.qmd
  sidebar:
    collapse-level: 1
    contents:
      - text: Home
        file: index.qmd
        style: floating
      - section: Articles
        contents:
          - text: Getting Started
            file: vignettes/getting-started.qmd
      - section: Reference
        contents:
          - text: darwin_variant
            file: man/darwin_variant.qmd
          - text: expect_snapshot_data
            file: man/expect_snapshot_data.qmd
          - text: expect_snapshot_object
            file: man/expect_snapshot_object.qmd
          - text: platform_variant
            file: man/platform_variant.qmd
          - text: snapr-package
            file: man/snapr-package.qmd
          - text: system_os
            file: man/system_os.qmd
      - text: News
        file: NEWS.md
      - text: License
        file: LICENSE.md
format:
  html:
    code-link: true
    theme:
      light: default
      dark: darkly
    css: styles.css
    number-sections: false
    code-fold: show
    echo: true
    code-copy: true
    code-overflow: scroll
    title-block-style: none
    toc: true
    grid:
      sidebar-width: 340px
      margin-width: 340px
